<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\lib\</BaseOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>VL.Stride.Rendering.Voxels</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Voxels" Version="$(StrideVersion)" GeneratePathProperty="true" />
    <PackageReference Include="VL.Core" Version="$(VLVersion)" />
    <PackageReference Include="VL.Stride.Runtime" Version="$(VLVersion)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Core.Assets.CompilerApp" Version="$(StrideVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>build;buildTransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="_CopyStrideVoxelsAssetsLocal" AfterTargets="Build">
    <ItemGroup>
      <_StrideVoxelsLocalAssetFiles Include="$(PkgStride_Voxels)\stride\Assets\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(_StrideVoxelsLocalAssetFiles)" DestinationFiles="@(_StrideVoxelsLocalAssetFiles->'$(MSBuildProjectDirectory)\..\shaders\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
